### PR TITLE
2352 - RTL: Colorpicker menu arrows advance oppositely

### LINKED ISSUE #2352: RTL: using the arrows in colorpicker goes the wrong way
**Describe the bug**
I'm not sure that this is a problem, cause i'm not sure how the keyboards works for those using RTL. But it might be so I'll report it for now, maybe someone else knows?
The issue is that when I the colorpicker and try to select a color using the keyboard arrows it moves in the opposite direction (right when I click left arrow and left when I click the right)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-index?locale=ar-SA
2. Click on the colorpicker to open it
3. Move around in the colorpicker using the left and right arrow

**Expected behavior**
I think that the selection should move in the direction of the arrow even in RTL

**Version**

- ids-enterprise: 4.18.1

**Screenshots**
-

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
As I mentioned I am not sure if key codes are switched or something for RTL keyboards? but probably not so I think this is a bug. If not then please close this ticket :)

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
When in RTL, the colorpicker left and right arrows advance opposite to their native direction. This PR fixes that issue by adding a RTL check and swapping the key events appropriately.

**Related github/jira issue (required)**:
Closes #2352 .

**Steps necessary to review your pull request (required)**:
- Pull branch, run app
- Visit http://localhost:4000/components/colorpicker/example-index.html & http://localhost:4000/components/colorpicker/example-index.html?locale=ar-EG (RTL)
  - Open colorpicker, focus into colorpicker menu, ensure left and right arrows advance correctly (left is left and right is right)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/popupmenu/popupmenu.js [hunk 1]
```diff
@@ -857,6 +857,7 @@ PopupMenu.prototype = {
 
   handleKeys() {
     const self = this;
+    const isRTL = document.querySelector('html').dir === 'rtl';
```
Comment (tmcconechy) [inline src/components/popupmenu/popupmenu.js]: Using `Locale.isRTL` would avoid a DOM selection. but safest way to do that is just using it in the event as it may not be set yet on init. So probably remove this line...

File: src/components/popupmenu/popupmenu.js [hunk 2]
```diff
@@ -1047,7 +1048,7 @@ PopupMenu.prototype = {
         }
 
         // Up on Up
-        if ((!isPicker && key === 38) || (isPicker && key === 37)) {
+        if ((!isPicker && key === 38) || (isPicker && key === (isRTL ? 39 : 37))) {
```
Comment (tmcconechy) [inline src/components/popupmenu/popupmenu.js]: Use `Locale.isRTL()` here?

File: src/components/popupmenu/popupmenu.js [hunk 3]
```diff
@@ -1085,7 +1086,9 @@ PopupMenu.prototype = {
         }
 
         // Down
-        if ((!isPicker && key === 40) || (isPicker && key === 39 && !isAutocomplete)) {
+        if ((!isPicker && key === 40)
+          || (isPicker && key === (isRTL ? 37 : 39))
```
Comment (tmcconechy) [inline src/components/popupmenu/popupmenu.js]: Use `Locale.isRTL()` here?

File: test/components/colorpicker/colorpicker.e2e-spec.js [hunk 4]
```diff
@@ -410,3 +410,24 @@ describe('Colorpicker sizes tests', () => {
     });
   }
 });
+
+describe('Colorpicker RTL left and right keys test', () => {
```
Comment (tmcconechy) [inline test/components/colorpicker/colorpicker.e2e-spec.js]: Do we have a non isRTL test? That would be nice. Seems like a good test

Comment (davidcarlsonberg) [reply test/components/colorpicker/colorpicker.e2e-spec.js]: Yes, there's a non RTL one for keyboard selection in the e2e file.
