### PR TITLE
2831 - Close Application Menu when clicking on Popupmenu Trigger Buttons

### LINKED ISSUE #2831: Toolbar button click does not dismiss application menu on mobile.
**Describe the bug**
Toolbar button click does not dismiss application menu on mobile.

**To Reproduce**

Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
Open Developer Tools - Toggle Device toolbar to iPhone
Click on the toolbar button, it should dismiss the menu.

**Expected behavior**
Clicking toolbar button on application menu on mobile should dismiss the menu.

**Version**

- ids-enterprise: v4.19.0-dev.20190424

**Screenshots**
GIT#2831

**Platform**
 - Device: iPhone 6/7/8

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR enables the closing of Application Menus when clicking/tapping on Popupmenu Trigger Buttons, if the environment allows for it.  Generally this will happen in a mobile setting where:
- the open application menu is covering the screen.
- the user clicks in the right-side area representing the "page", and taps directly on a Popupmenu trigger button.

Previously, this action wouldn't close the menu, which is the result when tapping anywhere else in the "page" area.

**Related github/jira issue (required)**:
Closes #2831

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, run the app.
- Open http://localhost:4000/components/applicationmenu/example-personalized-role-switcher
- Open a dev tools console, and on the device toolbar, enable a simulation of a mobile device such as an iPhone X.
- Make sure the Application Menu is open.
- Click on the "More Actions" menu button in the header toolbar.  After a brief delay (due to mobile interaction), the popupmenu should open, and the application menu should close.
- As a smoke test, disable the device simulation, and repeat these steps on a full-size page.  If the screen is above the "tablet" breakpoint, opening the popupmenu should NOT close the application menu.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/applicationmenu/applicationmenu.js [hunk 1]
```diff
@@ -769,6 +769,8 @@ ApplicationMenu.prototype = {
       self.openMenu(undefined, true);
     }).on('close-applicationmenu', () => {
       self.closeMenu();
+    }).on('dismiss-applicationmenu', () => {
```
Comment (tmcconechy) [inline src/components/applicationmenu/applicationmenu.js]: Do we need a teardown  on line `$(document).off('click.applicationmenu open-applicationmenu close-applicationmenu keydown.applicationmenu');` ?

Comment (EdwardCoyle) [reply src/components/applicationmenu/applicationmenu.js]: We sure do
