### PR TITLE
1736 - Handle text truncation with tooltip

### LINKED ISSUE #1736: Application Menu: Truncating of Text / Long Language Text Handling
**Describe the bug**
Truncated texts on application menu do not show tooltips.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html
2. Click on Level 1 Outbound Links and traverse through the application menu tree
3. Hover on 'Level 6 Outbound Link...'
4. There is no tooltip showing the full text.

**Expected behavior**
Tooltip should be present on a hover when text is truncated.

**Version**
- ids-enterprise: v4.17.0

**Screenshots**

**Platform**
 - Device: desktop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 72.0.3626.119 

**Additional context**
Related to https://github.com/infor-design/enterprise/issues/457

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
On Windows/IE where scrollbar appears when expanded accordion menu to a taller height and sometimes in Chrome, the tooltip was not actuating on truncated text. Padding was not taken in to account when calculating the width of the parent of the target text element.

**Related github/jira issue (required)**:
Closes #1736.
Related to #457.

**Steps necessary to review your pull request (required)**:
- Pull branch
- Run app
- Browse to http://localhost:4000/components/applicationmenu/test-six-levels-icons.html
- Expand into all elements and ensure tooltip appears over elements with truncated text. Feel free to test on IE as well.

### CODE REVIEW

File: src/components/accordion/accordion.js [hunk 1]
```diff
@@ -1543,7 +1543,7 @@ Accordion.prototype = {
 
     // Handle tooltip to show
     const handleShow = (elem) => {
-      if (elem.offsetWidth > elem.parentElement.offsetWidth) {
+      if (elem.offsetWidth > (elem.parentElement.offsetWidth - parseInt($(elem).parent().css('padding-left')))) {
```
Comment (EdwardCoyle) [inline src/components/accordion/accordion.js]:
```suggestion
      if (elem.offsetWidth > (elem.parentElement.offsetWidth - parseInt($(elem).parent().css('padding-left'), 10))) {
```

File: src/components/accordion/accordion.js [hunk 2]
```diff
@@ -1556,7 +1556,7 @@ Accordion.prototype = {
 
     // Handle tooltip to hide
     const handleHide = (elem) => {
-      if (elem.offsetWidth > elem.parentElement.offsetWidth) {
+      if (elem.offsetWidth > (elem.parentElement.offsetWidth - parseInt($(elem).parent().css('padding-left')))) {
```
Comment (EdwardCoyle) [inline src/components/accordion/accordion.js]:
```suggestion
      if (elem.offsetWidth > (elem.parentElement.offsetWidth - parseInt($(elem).parent().css('padding-left'), 10))) {
```
