### PR TITLE
1458 - Splitter drag handle icon

### LINKED ISSUE #1458: Splitter: Character sometimes renders incorrectly
**Describe the bug**
Very occasionally the character used for the splitter drag handle renders incorrectly.

**To Reproduce**
Cannot consistently reproduce, happens intermittently, perhaps latency dependent? 

**Expected behavior**
Ideally, this character should be replaced with an SVG icon that wouldn't be susceptible to character encoding problems or other text-related oddities. 

**Version**
Has happened in all versions

**Screenshots**
image

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 71.0.3578.98 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes an issue where the drag handle characters sometime render incorrectly. Changes the drag handle to an svg icon.

**Related github/jira issue (required)**:
closes #1458 

**Steps necessary to review your pull request (required)**:
- pull and build branch
- go to http://localhost:4000/components/splitter and check the examples. Make sure the drag handle is rendering properly.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

File: src/components/splitter/splitter.js [hunk 1]
```diff
@@ -66,6 +66,7 @@ Splitter.prototype = {
     const direction = s.axis === 'x' ? 'left' : 'top';
     const thisSide = parent.is('.content') ? parent.parent() : parent;
     const defaultOffset = 299;
+    const dragHandle = $('<div class="splitter-drag-handle"><svg class="icon"><use xlink:href="#icon-drag"/></svg></div>');
```
Comment (tmcconechy) [inline src/components/splitter/splitter.js:69]: I think just change this to use the `$.createIcon(` function. This will fix a few issues with just plain SVG's like basetag in the head and some IE append bugs. So we filter all icon creation through that function

**Comment by ericangeles** [comment]
All good to me. Just noticed a minor color issue when you hover, on high contrast variant uplift theme. The icon is really hard to see. This issue occurs to all pages.

draggable

**Comment by tmcconechy** [comment]
yeah i think just dial back the colors in uplift high contrast so its the same or similar to:

http://localhost:4000/components/splitter/example-index.html?theme=soho&variant=contrast

Its actually the opposite of higher contrast... I would say turn the backcolor in soho contrast down one on the drag state then use the same colors in uplift contrast

**Comment by jmacaluso711** [comment]
Using the tokens.. so they are slightly different between soho and uplift, but should be pretty close

**Comment by tmcconechy** [comment]
The only thing i still see is on http://localhost:4000/components/splitter/example-index.html?theme=uplift&variant=light (uplift theme). The icon is a lot smaller than it was before on master.

Its a little off center too there but i think if we make it closer to the same size as before it would be centered?
