### PR TITLE
4693 - Add new clear callback to lookup

### LINKED ISSUE #4693: Datagrid: Need to be notified when clearable filter icon is clicked
Describe the bug
Not notified when the clearable filter icon is clicked.  Issue exists when the grid options has filterWhenTyping set to false.

1. Using 'test-lookup-filter.html'
2. Add the property of filterWhenTyping: false to the grid options
3. Go to 'test-lookup-filter.html'
4. Perform a lookup on the filter row for Product Id column
5. Select a value
6. Click on the clear icon on the filter row for Product Id column 

Landmark will need to notified to react to the filter value being cleared.

Version
Landmark is on v4.35.2

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:
Fixes #4693

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/test-lookup-filter-click-clear
- click on the lookup -> it will populate the lookup field and show the X (no filtering will happen as this wasnt the point)
- click on the clear X 
- check the console and you can see that the clear callback was called

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

File: src/components/lookup/lookup.js [hunk 1]
```diff
@@ -55,7 +55,10 @@ function addSuffixToAttributes(parentAttrs = [], childAttrs = [], suffix) {
  * @param {function} [settings.click] Provide a special function to run when the dialog opens to customize the interaction entirely.
  * @param {string} [settings.clickArguments={}] If a click method is defined, this flexible object can be passed
  * into the click method, and augmented with parameters specific to the implementation.
- * @param {string} [settings.field='id'] Field name to return from the dataset or can be a function which returns a string on logic
+ * @param {function} [settings.clear] Provide a special function to run when the clear x is pressed
+ * @param {string} [settings.clearArguments={}] If a clear method is defined, this flexible object can be passed
+ * into the clear method, and augmented with parameters specific to the implementation.
+  * @param {string} [settings.field='id'] Field name to return from the dataset or can be a function which returns a string on logic
```
Comment (tmcconechy) [inline src/components/lookup/lookup.js:61]:
```suggestion
* @param {string} [settings.field='id'] Field name to return from the dataset or can be a function which returns a string on logic
```

**Review by deep7102 — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
