### PR TITLE
2315-Datagrid: Restore Columns should restore columns hidden status

### LINKED ISSUE #2315: Datagrid: Restore Columns should restore columns hidden in the dialog
**Describe the bug**
Restore columns should also restore columns hidden in the personalize dialog.

**To Reproduce**
1. Go to http://4180-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
3. Open Personalize Columns
4. Hide all but two columns
5. Reload Page
6. IN the .. menu select reset to default

**Expected behavior**
Should go back to however the original columns based to the grid are.

**Version**
- ids-enterprise: [v4.76.12 to v4.19.0 at least]

### PR DESCRIPTION
**Pull request by marknolaninfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Make sure that restore columns will reset the hidden status to the original state set on the datagrid definition

**Related github/jira issue (required)**:
Closes #2315 

**Steps necessary to review your pull request (required)**:
Go to http://localhost:4000/components/datagrid/test-save-settings.html
Click on '....'
Open Personalize Columns
Hide all but two columns
Reload Page
IN the .. menu select reset to default

### CODE REVIEW

File: src/components/datagrid/datagrid.js [hunk 1]
```diff
@@ -4739,6 +4739,10 @@ Datagrid.prototype = {
         if (isHidden !== undefined) {
           columns[i].hidden = isHidden;
         }
```
Comment (tmcconechy) [inline src/components/datagrid/datagrid.js]: Small lint error (cant suggest) but move this up please https://travis-ci.com/infor-design/enterprise/jobs/208010616#L522
