### PR TITLE
1021 - Fixed rowactivated for ie11 with datagrid [v4.17.x]

### LINKED ISSUE #1021: Datagrid - need a mechanism to cancel a rowActivated event
Need a mechanism to cancel a rowActivated event.  Perhaps before a rowActivated event occurs, fire a before event where a return of false means the event should be ignored?  Or make the rowActivated event cancellable?

Landmark business case:
Have a parent list that drives a child list.  The user adds a record to the child list. The user then changes the active row on the parent list (which then changes the child list).  Before performing the rowActivated event, need to query the user as to whether the child list changes should be saved.

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Example page for rowactivated was not working with IE11.

**Related github/jira issue (required)**:
Closes #1021

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/datagrid/test-before-row-activated.html
- Open above link with IE11
- Click on any row to make it activated
- See `beforerowactivated` is triggered
- Then `rowactivated` is triggered

### CODE REVIEW

File: src/components/datagrid/datagrid.js [hunk 1]
```diff
@@ -6218,13 +6218,13 @@ Datagrid.prototype = {
     const findInRows = (rowNodes) => {
       let found = false;
       rowNodes.toArray().forEach((row) => {
-        row.querySelectorAll('td').forEach((cell) => {
+        [].slice.call(row.querySelectorAll('td')).forEach((cell) => {
```
Comment (tmcconechy) [inline src/components/datagrid/datagrid.js]: Did you mean to change this? I didnt think this would be the problem

Comment (deep7102) [reply src/components/datagrid/datagrid.js]: Yes, it was breaking in ie11 because `document.querySelectorAll` return a `node-list` its array like object not an array so this needs to convert to array before using the `forEach`

File: app/views/components/datagrid/test-before-row-activated.html [hunk 2]
```diff
@@ -80,20 +80,20 @@
...
+
+      setTimeout(function() {
+        var shouldGoAhead = true;
+        if (shouldGoAhead) {
+          deferred.resolve();
+        } else {
+          deferred.reject();
+          message({ type: 'error', msg: 'Row Not Activated (row: '+ args.row +')' });
+        }
+        console.log('Complete: Before Row Activated');
```
Comment (davidcarlsonberg) [inline app/views/components/datagrid/test-before-row-activated.html]: Maybe take this out as you have the toast notification?

Comment (deep7102) [reply app/views/components/datagrid/test-before-row-activated.html]: I would keep them in example page, so its easy to navigate the `Begin/Complete`

File: src/components/datagrid/datagrid.js (hunk 1 above)
Comment (EdwardCoyle) [reply src/components/datagrid/datagrid.js]: @deep7102 FYI I had this problem in a handful of components before and added [`utils.getArrayFromList()`](https://github.com/infor-design/enterprise/blob/master/src/utils/utils.js#L1031-L1041) for the same purpose.  You may want to swap this line for that for consistency.

Comment (tmcconechy) [reply src/components/datagrid/datagrid.js]: That seems cleaner i find this syntax confusing too.
