### PR TITLE
2408 - Datagrid: placeholder on additional Formatters

### LINKED ISSUE #2408: Datagrid: placeholder on additional Formatters.
**Describe the bug**
A placeholder property can be placed on a datagrid column, but it is only visible when the Placeholder formatter is in use. We have a requirement to display a placeholder on a field that has a Lookup Editor, so it also requires that the Formatter is set to Lookup to trigger the control. 

Other Formatters that may require a placeholder:
* Decimal
* DropDown

**To Reproduce**
'http://localhost:4000/components/datagrid/example-placeholder.html' needs to be updated to provide an example.

**Expected behavior**
A placeholder can be added to a column without the requirement to use the Placeholder formatter.

**Version**
 v4.20.0 (master)

**Screenshots**

### PR DESCRIPTION
**Pull request by marknolaninfor**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Able to use the placeholder on additional Formatters:
* DropDown
* Lookup
* Decimal

**Related github/jira issue (required)**:
Closes #2408 

**Steps necessary to review your pull request (required)**:
1. goto 'http://localhost:4000/components/datagrid/example-placeholder.html'
2. A placeholder is visible on the additional Formatters

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/datagrid/datagrid.formatters.js [hunk 1]
```diff
@@ -515,8 +555,20 @@ const formatters = {
         }
       }
     }
+
```
Comment (tmcconechy) [inline src/components/datagrid/datagrid.formatters.js]: These code blocks repeat a bit, i wonder if its possible to extract these three into a shared function?

Comment (marknolaninfor) [reply src/components/datagrid/datagrid.formatters.js]: Moved to a function

**Comment by tmcconechy** [comment]
Minor lint issue https://travis-ci.com/infor-design/enterprise/jobs/209866782#L525
