### PR TITLE
2266 - Fix Colorpicker swatches shifting in small viewport

### LINKED ISSUE #2266: Colorpicker is not shown correctly in smaller viewport
**Describe the bug**
If I try to use a colorpicker in a window that is not so high or slim the colors are rearranged even though the dialog could be larger so that it could look as usual.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/colorpicker
2. Make the browser a little slimmer, so the frame is a little bit smaller. (For example 7742 pixels)
3. Click the Colorpicker

Steps to reproduce 2:
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-index
2. Make the browser really short
3. click the color picker
4. See the error

**Expected behavior**
1. Since the view aren't really that small, it should be possible to show the color picker as large as it usually is and show the colors as usual.
2. Here there is alot of room horizontally and it seems strange that it drags one color down to the next line when it's the height and not the width that is the problem.

**Version**
- ids-enterprise: v 4.18.1

**Screenshots**
1. 
image

2. 
image

**Platform**
 - OS Version: windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
-

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes an issue where the color swatches shift when the colorpicker has a scrollbar. Adds a check for the colorpicker height and adds a class to modify the width to accommodate the scrollbar.

**Related github/jira issue (required)**:
closes #2266

**Steps necessary to review your pull request (required)**:
- pull branch
- go to http://localhost:4000/components/colorpicker/example-index.html and make sure the swatches don't shift over in a short viewport.

Screen Shot 2020-04-21 at 11 16 40 AM

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/popupmenu/popupmenu.js [hunk 1]
```diff
@@ -1427,6 +1427,8 @@ PopupMenu.prototype = {
       return;
     }
 
+    console.log(this.menu[0].offsetHeight);
```
Comment (tmcconechy) [inline src/components/popupmenu/popupmenu.js:1430]:
```suggestion
```

Comment (tmcconechy) [reply src/components/popupmenu/popupmenu.js:1430]: Not sure if this works to remove...
