### PR TITLE
3556 - Fix pipe character was removing values to lookup with datagrid

### LINKED ISSUE #3556: Datagrid: Lookup editor removes '|" pipe character when returning value
Describe the bug
A datagrid cell is using the editor Lookup.  When the lookup editor returns the value, it removes all characters following and including the '|' pipe character.  Landmark has legit values that contains the '|' pipe character.  

To Reproduce
1. Using the attached test-editor-lookup-with-pipe.html 
2. Click on a Product Name cell
3. Click on the lookup icon
4. Select the item with the Product Name of 'Pipe| Character' (its the last one)
5. Leave the cell being edited
6. Notice that the value place into the cell is just 'Pipe' and not 'Pipe| Character' 

Expected behavior
Full value is displayed, no truncation when the value contains '|' pipe character.  

Version
v4.27.0-dev

Browser:
Testing using Chrome

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- Fixed lookup editor was removing all characters following and including the '|' pipe character with Datagrid.
- Added support to Optional Chaining in Javascript and updated Babel and ESLint plugins.

**Related github/jira issue (required)**:
Closes #3556

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to http://localhost:4000/components/datagrid/test-editable-lookup-with-pipe.html
- Open lookup for any cell in column `Product Name`
- Select value from lookup `Pipe | Character` (its the last one)
- Click somewhere else to blur out from cell
- See the picked value should remain fine

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
To other reviewers: give this an `npm prune && npm i` before trying to build to make sure the upgraded plugins are installed.

File: src/components/lookup/lookup.js [hunk 1]
```diff
@@ -693,7 +693,7 @@ Lookup.prototype = {
       }
 
       if (typeof this.settings.match !== 'function' &&
-        data[i][field].toString() === value.toString()) {
+        data[i][field]?.toString() === value?.toString()) {
```
Comment (EdwardCoyle) [inline src/components/lookup/lookup.js]: This is fantastic 💯
