### PR TITLE
502/503 - Patch for Xss issues [v4.18.x]

### LINKED ISSUE #502: Data Grid Component: Alignment not correctly aligned for BOD sorting button
**Describe the bug**
[All browsers] Data Grid Component: Alignment not correctly aligned for BOD sorting button

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-rtl-text.html?locale=ar-SA'
2. Click on the "BOD sorting button
3. Across all browsers and devices the button is misaligned 
4. Please see screen shot attached

**Expected behavior**
All sort buttons on the data grid should be aligned correctly

**Screenshots**
bs_win10_ie_11 0 1

**Platform**
 - All Browsers

**Additional context**
This issue is related to jira: https://jira.infor.com/browse/SOHO-6410

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This is a patch for 4.18.2. It addresses two XSS issues found in autocomplete and dropdown.

**Related github/jira issue (required)**:
Fixes infor-design/enterprise-ng#502
Fixes infor-design/enterprise-ng#503
Fixes infor-design/enterprise-ng#511

**Steps necessary to review your pull request (required)**:
- open the console
- http://localhost:4000/components/autocomplete/test-xss-security.html
- type '<'
- check the console, should be no CSP errors or any document alerts.

http://localhost:4000/components/dropdown/test-xss.html
- open the console
- open the list
- select the item with the script code in it
- check the console, should be no CSP errors or any document alerts.

http://localhost:4000/components/modal/test-xss.html
- open the console
- open click the button
- check the console, should be no CSP errors or any document alerts.

Also adding a test to NG on a separate PR

---

- [ ] Upon merge, send email to NPM security staff so they can release an advisory

### CODE REVIEW

**Comment by davidcarlsonberg** [comment]
@tmcconechy I think the second test page you mention in the description is incorrect?

**Comment by tmcconechy** [comment]
Hmm both pages seems like they are in the PR?

**Comment by davidcarlsonberg** [comment]
My bad, was looking at 4.18.x, not your specific branch.

**Comment by tmcconechy** [comment]
We will just have to merge this when its time. This branch does not have a lot of the test fixes on master anymore.

File: src/components/dropdown/dropdown.js [hunk 1]
```diff
@@ -864,7 +864,7 @@ Dropdown.prototype = {
     }
 
     if (this.settings.empty && opts.length === 0) {
-      this.pseudoElem.find('span').html(`<span class="audible">${this.label.text()} </span>`);
+      this.pseudoElem.find('span')[0].innerHTML = `<span class="audible">${this.label.text()} </span>`;
```
Comment (clepore) [inline src/components/dropdown/dropdown.js]: Any reason we switch from `.html` to `.innerHTML`?

File: src/components/modal/modal.js [hunk 2]
```diff
@@ -176,7 +177,7 @@ Modal.prototype = {
 
     this.element = $(`${'<div class="modal">' +
         '<div class="modal-content" style="max-width: '}${this.settings.maxWidth ? this.settings.maxWidth : ''}px${'">' +
-          '<div class="modal-header"><h1 class="modal-title">'}${this.settings.title}</h1></div>` +
+          '<div class="modal-header"><h1 class="modal-title">'}${xssUtils.stripTags(this.settings.title, '<div><span><a><small><img><svg><i><b><use><br><strong><em>')}</h1></div>` +
```
Comment (clepore) [inline src/components/modal/modal.js]: It'd be safer/cleaner to read if you sanitized the title, and any other html setting at the very beginning (in case they are used somewhere else in the code) and as a separate initiative instead of running functions in interpolated areas of a larger string.

Comment (tmcconechy) [reply src/components/modal/modal.js]: Agreed working on that now.

File: src/components/dropdown/dropdown.js (hunk 1 above)
Comment (tmcconechy) [reply src/components/dropdown/dropdown.js]: This actually fixes the problem. Also from experience veracode prefers this so really just jumping ahead to avoid a scan error. But looking at this again now `DOM.html` is probably better to use.

**Comment by tmcconechy** [comment]
@clepore Made the fixes as suggested. Thanks!
I'm hoping the tests pass as i dont really want to keep cherry picking tests from master as it is quite faor behind on this branch
