### PR TITLE
2647 - Slider: Colors object uses old theme names

### LINKED ISSUE #2647: Slide demo is failing with javascript error
**Describe the bug**
Slider demo is failing when using 'very-poor' color.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/slider/example-colors-and-ticks.html
2. Open your devtools and see console error and notice the slider component does not actually work.

**Expected behavior**
No error and slider w/'very-poor' tick should work. 

**Version**
4.21

**Screenshots**
image

### PR DESCRIPTION
**Pull request by davidcarlsonberg**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
The colors object is using outdated theme names (pre introduction of uplift) and returning undefined.

**Related github/jira issue (required)**:
Closes #2647 

**Steps necessary to review your pull request (required)**:
- Pull branch, build, run app
- Visit http://localhost:4000/components/slider/example-colors-and-ticks.html and http://localhost:4000/components/slider/example-vertical.html
  - ensure the slider demo works as expected

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

File: src/components/slider/slider.js [hunk 1]
```diff
@@ -937,7 +937,7 @@ Slider.prototype = {
         'very-good': '#76b051',
         superior: '#488421'
       },
-      'high-contrast': {
+      'contrast': {
```
Comment (tmcconechy) [inline src/components/slider/slider.js]:
```suggestion
      contrast: {
```
