### PR TITLE
1130 - Math.sign error on rating component in ie11 [v4.12.x]

### LINKED ISSUE #1130: Rating Component: Getting Webpage error on Win 10 IE 11 when I select or deselct a rating
**Describe the bug**
Rating Component: Getting Webpage error on Win 10 IE 11 when I select or deselct a rating

**To Reproduce**
1. Go to url: http://4120-rc1-enterprise.demo.design.infor.com/components/rating/example-index.html
2. Click on one of the rating stars
3. A popup window stating the following appears" Webpage Error"

**Expected behavior**
No error page should appear when selecting a rating

**Screenshots**
rating error1

**Platform**
  -Win 10 IE 11

**Additional context**
Done

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
IE 11 was giving an error on the rating component because IE 11 doesnt not have `Math.rating`

**Related github/jira issue (required)**:
Closes #1130

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/rating/list
- test all these pages on IE 11 and Chrome...

### CODE REVIEW

**Comment by tmcconechy** [comment]
- Can't rate as a half star (1.5, 2.5, 3.5, etc.)
This is a known issue, there is no way to do it... Half star is "readonly"

- Reset to zero stars doesn't return a selected star to unrated state
Im not 100% sure what you mean here. Can you elaborate?

**Comment by davidcarlsonberg** [comment]
rating

**Comment by tmcconechy** [comment]
Good find, pushed a fix for that.

File: src/components/rating/rating.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ Rating.prototype = {
       if (i < value) {
         input.addClass('is-filled').removeClass('is-half');
       } else {
-        input.removeClass('is-filled').removeClass('is-half');
+        input.removeClass('is-filled').removeClass('is-half').prop('checked', false);
```
Comment (davidcarlsonberg) [inline src/components/rating/rating.js]: Maybe?:
`input.removeClass('is-filled is-half').prop('checked', false);`
