### PR TITLE
1011 - undefined issue in dropdown fail [v4.12.x]

### LINKED ISSUE #1011: Dropdown with Icons: Searching in IE causes the icons to disappear and replaced with "undefined"
**Describe the bug**
Dropdown with Icons: Searching in IE causes the icons to disappear and replaced with "undefined".

**To Reproduce**
1. Go to http://localhost:4000/components/dropdown/example-icons.html in **Windows IE**
2. Type "icon" in the dropdown field
3. Notice that the icons will disappear and replaced by "undefined"

**Expected behavior**
Icons should not disappear when searching with the dropdown field

**Screenshots**
screen shot 2018-10-16 at 6 50 03 pm

**Platform**
 - Windows IE

**Additional context**
No additional context.

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Just a follow-up fix for the QA Test fail issue.

**Related github/jira issue (required)**:

Closes #1011 

**Steps necessary to review your pull request (required)**:

### CODE REVIEW

File: src/components/dropdown/dropdown.js [hunk 1]
```diff
@@ -1057,7 +1057,15 @@ Dropdown.prototype = {
...
 
       const text = a.text();
-      const icon = (li.children('a').find('svg').length !== 0) ? li.children('a').find('svg')[0].outerHTML : '';
+      let icon = '';
+
+      if (li.children('a').find('svg').length !== 0) {
+        if (li.children('a').find('svg')[0].outerHTML) {
+          icon = li.children('a').find('svg')[0].outerHTML;
+        } else {
+          icon = new XMLSerializer().serializeToString(li.children('a').find('svg')[0]);
```
Comment (EdwardCoyle) [inline src/components/dropdown/dropdown.js]: @tjamesallen15 good solution for the missing `outerHTML` on SVG elements... I think you could safely just grab the HTML this way and not even worry about checking for the existence of outerHTML here.  SVG elements won't have it.

**Comment by tjamesallen15** [comment]
Thanks for those replies @tmcconechy  @EdwardCoyle
