### PR TITLE
4160 - Locale and datepicker bugs with ar-SA (umalqura) [v4.30.x]

### LINKED ISSUE #4160: Datepicker: setValue() should accept a string and to- and fromGregorian working inversely
**Describe the bug**
When calling setValue() with a value string formatted as MMdd in umalqura, the value is not set. Additionally when using toGregorian and fromGregorian with the same locale, ie en-US, the value being formatted is in umalqura.

[test-set-value.zip](https://github.com/infor-design/enterprise/files/4933323/test-set-value.zip)

**To Reproduce**
1. Unzip the above and place into \app\views\components\datepicker directory
2. Go to 'http://localhost:4000/components/datepicker/test-set-value.html'
3. Error - the beginning database values of 2020 were converted to umalqura dates
4. Open new browser tab and go to "http://localhost:4000/components/datepicker/test-set-value.html?locale=ar-SA'
5. Error - the beginning database values were not converted; browser console has error of 'Uncaught TypeError: Cannot read property '2' of null'

**Expected behavior**

**Version**

- ids-enterprise: [4.30]

**Screenshots**
image
image

**Platform**
 - All

**Additional context**
This test is an example of how Landmark transforms dates, from data to display and display to data

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added several fixes uncovered on a new test page. See steps and is covered by tests.

**Related github/jira issue (required)**:
Fixes #4160 

**Steps necessary to review your pull request (required)**:
**Main issue**
- go to http://localhost:4000/components/locale/test-set-value.html
- each field should fill in with an arbitrary date (selecting a new date will fill the bottom set of fields)
- go to http://localhost:4000/components/locale/test-set-value.html?locale=ar-SA
- each field should fill in with an arbitrary date (selecting a new date will fill the bottom set of fields)
- the problem was the MMdd Field wasnt working and neither was yyyyMM Field

**Supplemental issue**
- on http://localhost:4000/components/locale/test-set-value.html?locale=ar-SA
- open the picker on the timestamp example and click today
- reopen again and pick one week up (19th)
- the times were turning to null (this should not happen now)

Don't worry if longer dates are partly cut off.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by jmacaluso711** [comment]
Only issue I'm seeing is here http://localhost:4000/components/locale/test-set-value.html?locale=ar-SA in the MMMMdd. Showing NaNNaN after selection

Screen Shot 2020-07-17 at 1 49 34 PM

File: src/components/datepicker/datepicker.js [hunk 1]
```diff
@@ -1784,9 +1784,9 @@ DatePicker.prototype = {
       !periodValue) && parseInt(hours, 10) === 12) ? 0 : hours;
 
     if (date instanceof Array) {
-      date[3] = hours;
-      date[4] = minutes;
-      date[5] = seconds;
+      date[3] = hours ? parseInt(hours, 10) : date[3];
+      date[4] = minutes ? parseInt(minutes, 10) : date[4];
+      date[5] = seconds ? parseInt(seconds, 10) : date[4];
     } else {
```
Comment (fitzorama) [inline src/components/datepicker/datepicker.js:1790]: should that be 
```suggestion
   date[5] = seconds ? parseInt(seconds, 10) : date[5];
```

File: src/components/datepicker/datepicker.js [hunk 2]
```diff
@@ -1784,9 +1784,9 @@ DatePicker.prototype = {
       !periodValue) && parseInt(hours, 10) === 12) ? 0 : hours;
 
     if (date instanceof Array) {
-      date[3] = hours;
-      date[4] = minutes;
-      date[5] = seconds;
+      date[3] = hours ? parseInt(hours, 10) : date[3];
+      date[4] = minutes ? parseInt(minutes, 10) : date[4];
+      date[5] = seconds ? parseInt(seconds, 10) : date[4];
```
Comment (fitzorama) [inline src/components/datepicker/datepicker.js:1789]: should this be >
```suggestion
      date[5] = seconds ? parseInt(seconds, 10) : date[5];
```

**Comment by tmcconechy** [comment]
@fitzorama @jmacaluso711 @deep7102 

Made fixes as noted. And updated the example for Mike.
