### PR TITLE
2107 - Fixes spinbox tolerance on long press

### LINKED ISSUE #2107: FieldOptions: Border misaligned
**Describe the bug**
The border is a pixel off.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/field-options/example-index.html
2. Click in the first field
3. See error

**Expected behavior**
Expect the options border to be up a piXel

**Version**
- ids-enterprise:  v4.18.x

**Platform**
 - Browser Name [chrome]

**Additional context**
Seems to work to add `top: -1px` but all browsers should be tested for the best solution

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

QA failed #2017 on edge as it appeared like it was inserting twice on click. This is really just the long press but it seems a little more sensitive on edge. Also added autocomplete off as saw the browser autocomplete popping up on testing.

**Related github/jira issue (required)**:
Fixes #2107

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/field-options/example-index.html
or
http://localhost:4000/components/spinbox/example-index.html

- click once on + and - and it should add or subtract one
- press down on either button and it should more slowly count up and down
- try on edge

### CODE REVIEW

**Comment by tmcconechy** [comment]
Ok 250 would be fine can you edit the pr and i'll accept?

File: src/components/spinbox/spinbox.js [hunk 1]
```diff
@@ -278,7 +278,7 @@ Spinbox.prototype = {
       if ($(e.currentTarget).is(':hover')) {
         self.handleClick(e);
       }
-    }, 140);
+    }, 300);
```
Comment (davidcarlsonberg) [inline src/components/spinbox/spinbox.js]:
```suggestion
    }, 250);
```
