### PR TITLE
1025 - popupmenu multi controls

### LINKED ISSUE #1025: Popupmenu breaks when shared between multiple controls.
**Describe the bug**

Use of a `popupmenu` component with several different html elements as context menus does not work as expected if the element hosting the `popupmenu` is removed from the DOM (which is often the case with angular components).

This issue is not just an angular issue, but can also be replicated in raw enterprise widgets.

**To Reproduce**
The following markup creates two inputs, each sharing the same popup menu. Deleting the first input prevents the context menu from appearing for the remaining input.

```html
    <button id="popdown-destroy" class="btn" type="button">
      <span>Destroy</span>
    </button>

    <div class="field" id="field1">
      <label for="input-menu">Label</label>
      <input type="text" value="Right Click Me" id="input-menu"/>
    </div>

    <div class="field" id="field2">
      <label for="input-menu2">Label2</label>
      <input type="text" value="Right Click Me" id="input-menu2"/>
    </div>

    <ul id="action-popupmenu" class="popupmenu">
      <li><a href="#">Cut</a></li>
      <li><a href="#">Copy</a></li>
      <li><a href="#">Paste</a></li>
    </ul>
```

```javascript
    // Share the popupmenu with the two context menus.
    const contextMenu = $('#input-menu');
    contextMenu.popupmenu({trigger:'rightClick', menu: "action-popupmenu", attachToBody: true})
    const contextMenuApi = contextMenu.data('popupmenu');

    const contextMenu2 = $('#input-menu2')
    contextMenu2.popupmenu({trigger:'rightClick', menu: "action-popupmenu", attachToBody: true});
    const contextMenuApi2 = contextMenu2.data('popupmenu');

    const popupMenu = $('#action-popupmenu');
    popupMenu.popupmenu({ attachToBody: true });
    const popupMenuApi = popupMenu.data('popupmenu');

    // This emulates an *ngIf on the first field, where it's presence is toggled.
    $('#popdown-destroy').click(() => {
      // turn off events
      contextMenu.off();

      // destroy the api
      contextMenuApi.destroy();

      // Remove the context.
      contextMenu.parent().remove();
    });
```

**Expected behavior**

I would expect the `popupmenu` to continue to work.

**Screenshots**

N/A

**Platform**

**Additional context**

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
A single `popupmenu` with multiple context menus stops working when one of the triggers is removed from the DOM. Added a setting called `duplicateMenu` to check against and clone the `popupmenu`

**Related github/jira issue (required)**:
closes #1025 

**Steps necessary to review your pull request (required)**:
* go to test page http://localhost:4000/components/popupmenu/test-multiple-context-menu-destroy.html
* click Destroy button and check that the `popupmenu` still works

### CODE REVIEW

File: src/components/popupmenu/popupmenu.js [hunk 1]
```diff
@@ -1292,6 +1308,11 @@ PopupMenu.prototype = {
       height: this.menu[0].offsetHeight
     };
 
+    // if (!this.menu.parent().is('.popupmenu-wrapper')) {
```
Comment (tmcconechy) [inline src/components/popupmenu/popupmenu.js]: Could just remove this.
