### PR TITLE
8352 - [Preview] Datagrid Contextual Toolbar Hide Function

### LINKED ISSUE #8352: [Preview] Datagrid: Contextual toolbar is closed when clicking buttons
**Describe the bug**
The data grid contextual toolbar is closed when any button is clicked. There are 2 problems with this:

1. If the button has a menu, the menu will still be displayed even though you can no longer see the button.
2. The data grid selection that caused the toolbar to be displayed is still active, so you now have an active selection but no toolbar with actions to perform on the selected row.

**Steps to reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-contextual-toolbar-hide.html
2. Select an item
3. Click the button in the toolbar

**Expected behavior**
I don't think the toolbar should close at all when a button is clicked. Not sure if this is intended? If it is, then:

1. It should NOT close when clicking menu buttons, or anything else that has a dropdown, dialog or similar.
4. It should not keep the selection, since the selection is then pointless, and you have to deselect/select again to show the toolbar.

**Version**

- ids-enterprise: 4.92.0-dev.1

**Screenshots**

https://github.com/infor-design/enterprise/assets/4991954/aa613430-2cc4-459d-83f8-a0d4363cfec9

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Caused by https://github.com/infor-design/enterprise/pull/8284

### PR DESCRIPTION
**Pull request by tjamesallen15**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix contextual toolbar auto hide when performing action.

**Related github/jira issue (required)**:
Closes #8352 
Related https://github.com/infor-design/enterprise-ng/issues/1580

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-contextual-toolbar-hide.html
- Open `Developer Console`
- Click one checkbox to show the toolbar
- Click `Perform Action`
- Toolbar should not hide
- Click `Hide Action`
- Toolbar should hide
- Click one checkbox to show the toolbar
- Deselect the checkbox selected to hide the toolbar
- Click the select all to show the toolbar
- Deselect the select all to hide the toolbar

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

File: src/components/datagrid/datagrid.js [hunk 1]
```diff
@@ -8056,6 +8048,18 @@ Datagrid.prototype = {
     this.element.addClass('has-toolbar');
   },
 
+  /**
+   * Hides the contextual toolbar.
+   * @returns {void}
+   */
+  hideContextualToolbar() {
```
Comment (tmcconechy) [inline src/components/datagrid/datagrid.js:8055]: Make sure we add the NG types

**Review by tmcconechy — COMMENTED** [review]
Looks good, maybe just remove the other fix until later and fix lint.

File: src/components/cards/_cards-new.scss [hunk 2]
```diff
@@ -293,7 +293,7 @@
     padding-left: 16px;
     padding-right: 8px;
     padding-top: 0;
-    width: 360px;
+    // width: 360px;
```
[the remark this answers is not in the document]
Comment (tjamesallen15) [reply src/components/cards/_cards-new.scss]: done on this one!

File: src/components/datagrid/datagrid.js (hunk 1 above)
Comment (tjamesallen15) [reply src/components/datagrid/datagrid.js:8055]: done on this one!

**Comment by tmcconechy** [comment]
cc @anhallbe

File: src/components/cards/_cards-new.scss [hunk 3]
```diff
@@ -293,7 +293,6 @@
     padding-left: 16px;
     padding-right: 8px;
     padding-top: 0;
-    width: 360px;
```
Comment (tmcconechy) [inline src/components/cards/_cards-new.scss:296]: May not want to take this out here

**Review by ericangeles — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise/assets/102151352/557ece7e-5acb-407d-8f56-78853e5160ad
