### PR TITLE
Fixing field filter wrapper on dropdown fields

### LINKED ISSUE #179: Dropdowns on Field Filter don't display correctly
**Describe the bug**
Dropdowns aren't being wrapped correctly by the field filter control.

**To Reproduce**
Add this html to field-filter/example-index.html

     <div class="field">
      <label for="example-dropdown" class="label">Dropdown</label>
      <select id="example-dropdown" class="dropdown field-filter input-md">
        <option value=""></option>
        <option value="1">Inquiry</option>
        <option value="2">Setup</option>
      </select>
    </div>

1. Navigate to /components/field-filter/example-index.html
2. See error

**Expected behavior**
Dropdown should match how the other fields looks for field filter

**Screenshots**
image

**Platform**
 - All

### PR DESCRIPTION
**Pull request by Sovia**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixing the field filter wrapper for dropdowns

**Related github/jira issue (required)**:

[https://github.com/infor-design/enterprise/issues/179](https://github.com/infor-design/enterprise/issues/179)

**Steps necessary to review your pull request (required)**:
Navigating to the example-index.html in field filter should now look like:
image

**Closing issues**
`closes #179`

### CODE REVIEW

File: src/components/field-filter/field-filter.js [hunk 1]
```diff
@@ -125,7 +125,7 @@ FieldFilter.prototype = {
 
       // Add css classes
       this.field.addClass('fieldfilter-wrapper')
-        .find('div.dropdown span').addClass('audible');
+        .find('div.dropdown.no-init span').addClass('audible');
```
Comment (tmcconechy) [inline src/components/field-filter/field-filter.js]: Why is the no-init needed?

Comment (Sovia) [reply src/components/field-filter/field-filter.js]: Without the no-init, it was also adding the audible class to the span inside the dropdown field that was being wrapped. This caused the value to never appear selected when the dropdown wasn't open (even when a value was selected)

Comment (EdwardCoyle) [reply src/components/field-filter/field-filter.js]: We should find a way to do it without the `no-init` class being a dependency.  `no-init` isn't really supposed to be used directly by the components in this manner - it's meant as a tool for app developers to control the flow of component initialization.  If we use it internally and remove it automatically, it could cause unexpected results for an app developer depending on it.
