### PR TITLE
8709 - Added fix to guard for errors

### LINKED ISSUE #8709: DataGrid: Failed to set the 'innerHTML' property on 'Element'
**Describe the bug**
When I call the 'updateRow' method in datagrid.js, an error occured:
```
Failed to set the 'innerHTML' property on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
```

**To Reproduce**

Sorry for that it is not easy to reproduce, the error just occurred after we upgrading IDS from v4.91.0 to v4.91.1.
And in v4.91.0, our codes worked well.

**Expected behavior**

**Version**

- ids-enterprise: v4.91.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: 
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 124.0.6367.119 (Official Build) (64-bit)

**Additional context**
1.In firefox, it works well, the error occurred when I use the chrome browser.
2.For the codes in `updateCellNode` method in `datagrid.js` file:
`wrapper[0].innerHTML = formatted; `,
I am wondering if the above codes in IDS can be changed through some solutions:
**Solution 1:**
Define a new method which can avoid the xss attack, for example ```escapeHtml``` and then:
```wrapper.html(escapeHtml(formatted));```
**Solution 2:**
// If using innerHTML throws an exception, then use the fallback method.
```
try {
  wrapper[0].innerHTML = formatted;
} catch (e) {
  wrapper.empty().append(formatted);
}
```

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes for an unknown situation as noted on. 

**Related github/jira issue (required)**:
Fixed #8709

**Steps necessary to review your pull request (required)**:
- retest steps on https://github.com/infor-design/enterprise/pull/8447

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

File: src/components/datagrid/datagrid.js [hunk 1]
```diff
@@ -12042,9 +12042,9 @@ Datagrid.prototype = {
       const rect = el[0].getBoundingClientRect();
```
Comment (adamzhang1932) [inline src/components/datagrid/datagrid.js:12042]: Even though this line was committed before, I have one question for this:
if `el` is not `undefined`, and then `el[0].getBoundingClientRect()`  might have an error:
Cannot read properties of undefined (reading 'getBoundingClientRect').

**Comment by n-ace-ancog** [comment]
No issues found regarding previous implementation.

image

image

image

image

image

https://github.com/infor-design/enterprise/assets/156752175/ded2d751-dfc2-40a5-8347-fb9b355f2c58

**Review by glenlieorillo — DISMISSED** [review]
https://alt-fix-xss-enterprise.demo.design.infor.com/components/datagrid/example-editable.html - Passed

https://github.com/infor-design/enterprise/assets/102151352/5054ea54-f908-4be6-8256-0c9d0744da29

https://alt-fix-xss-enterprise.demo.design.infor.com/components/datagrid/example-editable-with-row-status.html - Passed

https://github.com/infor-design/enterprise/assets/102151352/b06b8357-3504-4566-a4b2-450ca6e72a61

https://alt-fix-xss-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup-mask.html - Passed

_Note: After tabbing out of the cell, it shows an empty cell._

https://github.com/infor-design/enterprise/assets/102151352/64f324d0-317f-4dd2-a29c-27dd822045ff

File: src/components/datagrid/datagrid.js (hunk 1 above)
Comment (ericangeles) [reply src/components/datagrid/datagrid.js:12042]: @adamzhang1932, it wouldn't, since there is a guard clause `if (el === undefined) return;` before that line.

See https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L12040

Comment (tmcconechy) [reply src/components/datagrid/datagrid.js:12042]: @adamzhang1932 @ericangeles i added a better guard here "just in case"

**Review by n-ace-ancog — APPROVED** [review]
Still working as expected:

image

**Review by ericangeles — APPROVED** [review]

**Review by ericangeles — APPROVED** [review]
