### PR TITLE
277 Fixed issue regarding tab content still being displayed after hid…

### LINKED ISSUE #277: Hidden Tabs Control: Tab contents are still displayed when the tab becomes hidden
**Describe the bug**
Tab contents are stiil shown when Tab was rehidden

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/tabs/example-hidden-tabs.html
2. Click Show Hidden Tabs button
3. Go to Tab # 5, contents of Tab # 5 will be shown
4. Click Hide Tabs 2 and 5 button while still on Tab # 5
5. Notice that the contents of Tab # 5 is still shown

**Expected behavior**
Tab number 5 should not be appearing

**Screenshots**
 - All Browsers 

**Additional context**
None

### PR DESCRIPTION
**Pull request by tmcastro**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- Fixed issue regarding tab content still being displayed after hiding selected tab
- http://localhost:4000/components/tabs/example-hidden-tabs.html

**Related github/jira issue (required)**:
Closes #277 

**Steps necessary to review your pull request (required)**:
- Click Show Hidden Tabs button
- Go to Tab # 5, contents of Tab # 5 will be shown
- Click Hide Tabs 2 and 5 button while still on Tab # 5
- Another tab should now be selected

### CODE REVIEW

File: src/components/tabs/tabs.js [hunk 1]
```diff
@@ -2666,8 +2666,15 @@ Tabs.prototype = {
     const tab = this.doGetTab(e, tabId);
 
     if (tab.is('.is-selected')) {
-      this.activatePreviousTab(tabId);
+      if (tab.prevAll('li.tab').not('.hidden').length > 0) {
```
Comment (tmcconechy) [inline src/components/tabs/tabs.js]: This seems to work well. But the activatePreviousTab is also used when disabling tabs.

So maybe this logic should just go into the activatePreviousTab function for better readability. 

Then once you do that test http://localhost:4000/components/tabs/test-disabled-change-tab.html as well for a similar bug.

**Comment by tmcastro** [comment]
[soho-277.zip](https://github.com/infor-design/enterprise/files/2338795/soho-277.zip)

I've attached a video of me testing the page. It looks fine on my end. I'll check on the e2e tests.
