### PR TITLE
1716 - Added QA fix for landscape stretch column and size columns equally [v4.17.x]

### LINKED ISSUE #1716: Datagrid: stretch column not working in Edge browser
**Describe the bug**
The stretch column does not work correctly and within the Edge browser a space can be seen.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-columns-stretch-column.html'

**Expected behavior**
The grid columns should fill the datagrid.

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 10
 - Browser Name Edge
 - Browser Version 40.15063.674.0

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added fixes for noted QA issues on 1716. Some things were not working perfectly when changing to landscape mode and the sizeColumnsEqually feature was broken. Also fixed one deprecation warning in the tests. Also removed one deprecation in datagrid as the function is actually different so the comment is incorrect

**Related github/jira issue (required)**:
Fixes #1716 

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/datagrid/test-columns-stretch-column.html
- open on an IOS device or browser stack
- turn the device to landscape mode (this should now work)

http://localhost:4000/components/datagrid/test-columns-equal.html
- all columns should be equal size with no horizontal scrollbar

### CODE REVIEW

**Comment by tmcconechy** [comment]
Hmmm thats exactly what i was trying to fix. Tried it on browser stack and in chrome debugger in ios mode and it worked? Did you update everything ok? Is that IOS (xcode sim?)

**Comment by davidcarlsonberg** [comment]
> Hmmm thats exactly what i was trying to fix. Tried it on browser stack and in chrome debugger in ios mode and it worked? Did you update everything ok? Is that IOS (xcode sim?)

Yup, iOS Xcode Simulator. I can send a video if it helps. I fetched latest, including your branch, so everything should be updated.

Also, there's a `console.log` in there you might want to take out.

File: src/components/datagrid/datagrid.js [hunk 1]
```diff
@@ -5612,6 +5609,13 @@ Datagrid.prototype = {
       }
     });
 
+    if (this.stretchColumn !== 'last') {
+      $(window).on('orientationchange.datagrid', () => {
+        console.log('oc');
```
Comment (davidcarlsonberg) [inline src/components/datagrid/datagrid.js]:
```suggestion
```
