### PR TITLE
2604 - Add support to short labels with wizard

### LINKED ISSUE #2604: Wizard: Show labels on mobile
**Describe the bug**
When on mobile (be design) only the current labels are shown. We need to think of some solutions to help usability.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/wizard/example-index.html
2. Resize to mobile size or use a mobile device
4. See that you cannot see what the next and previous steps are

**Expected behavior**
Consider some options to show the label such as:
- show the label up to ellipsis text
- long press the item or ellipsis text to show in a tooltip
- add ability to show abbreviated / shorter versions of the wizard text

**Version**
- ids-enterprise: [v4.20.0]

**Screenshots**
Screen Shot 2019-08-05 at 1 33 07 PM

**Platform**
 - Device: desktop mobile size or IOS or android

**Additional context**
This was noted in GoWidgets4.mp

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added support for short labels with wizard. If short labels not supplied it will add ellipsis to text and tooltip.

**Related github/jira issue (required)**:
Closes #2604

**Steps necessary to review your pull request (required)**:
http://localhost:4000/components/wizard/test-shortlabels.html
http://localhost:4000/components/wizard/test-shortlabels-dynamic.html
http://localhost:4000/components/wizard/test-labels-ellipsis.html
- Pull this branch and build/run the demo app
- Open above links
- Resize the browser window to small viewport
- See short labels or ellipsis in place

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

File: src/components/wizard/wizard.js [hunk 1]
```diff
@@ -10,7 +10,8 @@ const COMPONENT_NAME = 'wizard';
 
 // Component Default Settings
 const WIZARD_DEFAULTS = {
-  ticks: null
+  ticks: null,
+  ticksTemplate: '<a ng-click="handleClick()" class="tick {{state}}" href="{{href}}"><span class="label" data-shortlabel="{{shortLabel}}">{{label}}</span></a>'
```
Comment (tmcconechy) [inline src/components/wizard/wizard.js]:
```suggestion
  ticksTemplate: '<a class="tick {{state}}" href="{{href}}"><span class="label" data-shortlabel="{{shortLabel}}">{{label}}</span></a>'
```
